/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */




#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

// 0x4002 0C00 - 0x4002 0FFF GPIOD
// I'm using D2 which is the second pin above ground and is also second from the edge

// 0x4002 3800 - 0x4002 3BFF - RCC


/*
 * 0x4002 3800 - 0x4002 3BFF - RCC

6.3.9 RCC AHB1 peripheral clock enable register (RCC_AHB1ENR)
Address offset: 0x30 --- ADD TO BASE ADDRESS
Reset value: 0x0000 0000

Bit 3 GPIODEN: IO port D clock enable
Set and cleared by software.
0: IO port D clock disabled
1: IO port D clock enabled
 */

/*
 * Address of the Clock Control register (AHB1ENR)
0x40023800+0x30 = 0x40023830

Address of the GPIOD mode register (used to control mode)
0x40020C00 + 0x00 = 0x40020C00

Address of the GPIO output data register - used to write (GPIOx_ODR)
0x40020C00 + 0x14 = 0x40020C14
 */

// USE WINDOW - SHOW VIEW - SFR -- SHOWS REGISTERS

int main(void)
{
	uint32_t* pRccEn = (uint32_t*)0x40023830;
	uint32_t* pGpioMode = (uint32_t*)0x40020C00;
	uint32_t* pGpioOutput = (uint32_t*)0x40020C14;


	*pRccEn |= 0x08; // or operator, turning on 4th bit to enable clock

	// clear register
	*pGpioMode &= 0xFFFFFFCF;

	// set control mode

	*pGpioMode |= 0x10;


	// set HIGH

	*pGpioOutput |= 0x4;

    /* Loop forever */
	for(;;);
}
